-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 11:32:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema boost_mannager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boost_mannager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boost_mannager` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `boost_mannager` ;

-- -----------------------------------------------------
-- Table `boost_mannager`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boost_mannager`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `NombreCliente` VARCHAR(100) NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `Domicilio` VARCHAR(100) NOT NULL,
  `Responsable` ENUM('Empresa', 'Individuo') NOT NULL,
  `RUC` VARCHAR(45) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boost_mannager`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boost_mannager`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boost_mannager`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boost_mannager`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Factura` DATE NOT NULL,
  `Pago` ENUM('Contado', 'Cheque', 'Transferencia') NOT NULL,
  `Concepto` ENUM('Compra', 'Venta') NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `boost_mannager`.`Clientes` (`idClientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boost_mannager`.`Factura_Ordinaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boost_mannager`.`Factura_Ordinaria` (
  `idFactura_Ordinaria` INT GENERATED ALWAYS AS () VIRTUAL,
  `Cantidad` INT UNSIGNED NOT NULL,
  `Factura_idFactura` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  PRIMARY KEY (`idFactura_Ordinaria`),
  INDEX `fk_Factura_Ordinaria_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  INDEX `fk_Factura_Ordinaria_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Ordinaria_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `boost_mannager`.`Factura` (`idFactura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Factura_Ordinaria_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `boost_mannager`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `boost_mannager` ;

-- -----------------------------------------------------
-- procedure get_order_by_cust
-- -----------------------------------------------------

DELIMITER $$
USE `boost_mannager`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_order_by_cust`()
BEGIN
    DECLARE exist VARCHAR(50) DEFAULT 0;

    SELECT Nombre_User
        INTO exist
    FROM login_history
        WHERE Contraseña = 123456;

    IF exist = '' THEN DESCRIBE login_history;
    ELSE
        UPDATE login_history SET Nombre_User = 'CHUPA UN LIMON NIÑO' WHERE Contraseña = 123456;
    end if;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
